using Cbix.Core.Extraction;

namespace Cbix.UnitTests.Extraction;

/// <summary>
/// The strict half of the first agent call (story S01-14).
/// </summary>
/// <remarks>
/// <para>
/// Every test below is a refusal except the first three, and that ratio is the point. This parser is
/// where "agents propose, code disposes" is implemented for triage: each repair a parser is willing
/// to make transfers a decision from the pipeline to the model, and each one is invisible afterwards
/// - a defaulted field reads exactly like an extracted one.
/// </para>
/// <para>
/// The malformed payloads are written out rather than derived, deliberately: what is under test is
/// what a model might actually emit, and a payload generated by mutating a good one can only produce
/// the mutations somebody thought of.
/// </para>
/// </remarks>
public sealed class DocumentProfileParserTests
{
    private const string ValidProfile =
        """{"DocType":"Cross-Border Trading Legal Instruction","JurisdictionIso":"DE","DocRef":"CBTI-DE-2024","Version":"4.2","LayoutFamily":"contoso-country-manual-v4","Confidence":0.97}""";

    [Fact]
    public void Parse_ReadsTheContractDesignAppendixADeclares()
    {
        DocumentProfile profile = DocumentProfileParser.Parse(ValidProfile);

        Assert.Equal("Cross-Border Trading Legal Instruction", profile.DocType);
        Assert.Equal("DE", profile.JurisdictionIso);
        Assert.Equal("CBTI-DE-2024", profile.DocRef);
        Assert.Equal("4.2", profile.Version);
        Assert.Equal("contoso-country-manual-v4", profile.LayoutFamily);
        Assert.Equal(0.97d, profile.Confidence);
    }

    [Fact]
    public void ContractFields_AreExactlyDesignAppendixAsRecordShape()
    {
        // The prompt is built from this list and the parser enforces it, so the list IS the contract.
        // Pinned in its declared order because design Appendix A declares an order, and a positional
        // record whose fields were reordered would still compile while meaning something else.
        Assert.Equal(
            ["DocType", "JurisdictionIso", "DocRef", "Version", "LayoutFamily", "Confidence"],
            DocumentProfileParser.ContractFields);

        // And the list matches the record, so the two cannot drift silently in either direction.
        Assert.Equal(
            DocumentProfileParser.ContractFields.Order(StringComparer.Ordinal),
            typeof(DocumentProfile)
                .GetProperties()
                .Where(property => !string.Equals(property.Name, "EqualityContract", StringComparison.Ordinal))
                .Select(property => property.Name)
                .Order(StringComparer.Ordinal));
    }

    [Theory]
    [InlineData(0d)]
    [InlineData(1d)]
    public void Parse_AcceptsTheEndsOfTheUnitInterval(double confidence)
    {
        // Closed interval, both ends. A model that reports 0 is saying "I have no idea", which is a
        // legitimate and useful answer - it routes to review - and refusing it would turn the clearest
        // possible statement of uncertainty into an unparseable reply for no reason.
        DocumentProfile profile = DocumentProfileParser.Parse(WithConfidence(confidence.ToString("0.0", null)));

        Assert.Equal(confidence, profile.Confidence);
    }

    [Fact]
    public void Parse_UnwrapsACodeFenceBecauseThatIsTransportRatherThanContent()
    {
        // The single normalisation, and its whole justification is that it is total and deterministic:
        // a reply either is fenced or is not. Several providers emit a fence regardless of
        // instructions, and refusing every fenced reply would route perfectly good documents to a human
        // over presentation. What is NOT permitted is searching for JSON inside prose - see the next
        // test.
        DocumentProfile profile = DocumentProfileParser.Parse("```json\n" + ValidProfile + "\n```");

        Assert.Equal("DE", profile.JurisdictionIso);
    }

    [Fact]
    public void Parse_RefusesJsonEmbeddedInProseRatherThanHuntingForIt()
    {
        // The line the fence handling must not be read as crossing. "Find the JSON in here" is a
        // search, and a search that succeeds on the wrong substring produces a confident profile
        // nobody wrote - which is worse than the refusal it replaced.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse("Here is the profile you asked for: " + ValidProfile));

        Assert.Equal(DocumentProfileDefect.NotAJsonObject, error.Defect);
    }

    [Theory]
    [InlineData("I think this is a German trading manual.")]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("[1, 2, 3]")]
    [InlineData("\"DE\"")]
    [InlineData("{\"DocType\":\"x\",}")]

    // Fence-wrapped rubbish. Unwrapping a fence is transport handling, not a licence to accept what
    // is inside one, and these were measured safe but untested - which is the state in which a
    // later "harmless" tweak to Unfence quietly widens what the parser takes.
    [InlineData("```json\nI think this is a German trading manual.\n```")]
    [InlineData("```\n\n```")]
    [InlineData("```json\n[1, 2, 3]\n```")]
    [InlineData("```json\n{\"DocType\":\"x\"\n```")]
    public void Parse_RefusesAReplyThatIsNotTheContractObject(string reply)
    {
        DocumentProfileFormatException error =
            Assert.Throws<DocumentProfileFormatException>(() => DocumentProfileParser.Parse(reply));

        Assert.Equal(DocumentProfileDefect.NotAJsonObject, error.Defect);
    }

    [Fact]
    public void Parse_RefusesAMissingFieldRatherThanDefaultingIt()
    {
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(
                """{"DocType":"x","JurisdictionIso":"DE","DocRef":"r","Version":"1","Confidence":0.9}"""));

        Assert.Equal(DocumentProfileDefect.MissingField, error.Defect);
        Assert.Contains("LayoutFamily", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAnUndeclaredFieldRatherThanIgnoringIt()
    {
        // Ignoring it would hide a prompt and a schema drifting apart until something downstream needed
        // the answer that was really meant.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(WithExtra("\"Notes\":\"looks German\"")));

        Assert.Equal(DocumentProfileDefect.UndeclaredField, error.Defect);
        Assert.Contains("Notes", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesACaseVariantOfAContractField()
    {
        // 'docType' is not 'DocType'. A model that changed the casing changed what it believes the
        // schema is, and accepting both spellings would make the contract's shape a matter of taste.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(ValidProfile.Replace("\"DocType\"", "\"docType\"", StringComparison.Ordinal)));

        Assert.Equal(DocumentProfileDefect.UndeclaredField, error.Defect);
    }

    [Fact]
    public void Parse_RefusesARepeatedFieldRatherThanPickingOne()
    {
        // Which of two values for one field is "the" value is not a question a parser may decide, and
        // System.Text.Json's own last-one-wins would have decided it silently.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(WithExtra("\"JurisdictionIso\":\"CH\"")));

        Assert.Equal(DocumentProfileDefect.DuplicateField, error.Defect);
        Assert.Contains("JurisdictionIso", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_RefusesAReplyThatBothRepeatsAndOmitsAFieldWithoutThrowingAnUncaughtException()
    {
        // THE REGRESSION. Six properties, every name declared, one repeated and one absent - the two
        // errors cancelled in the count the earlier implementation checked, so the reply passed the
        // gate and the omitted field's GetProperty then threw KeyNotFoundException. That is not a
        // DocumentProfileFormatException, so TryParse's catch never saw it: it escaped the parser,
        // escaped the triage executor, and killed the run. The boundary neither accepted the reply nor
        // refused it - it threw - and the document that most needed a human reached nobody. A model's
        // reply is attacker-influenced text (prompt injection through a supplied document reaches it),
        // so this shape is reachable deliberately and not only by accident.
        //
        // Asserted through BOTH entry points, because the defect was in what escaped rather than in
        // what was returned: Parse must raise the typed refusal, and TryParse must REPORT it rather
        // than let anything else through.
        const string RepeatsAndOmits =
            """{"DocType":"Cross-Border Trading Legal Instruction","DocType":"duplicate","JurisdictionIso":"DE","DocRef":"CBTI-DE-2024","Version":"4.2","Confidence":0.97}""";

        DocumentProfileFormatException error =
            Assert.Throws<DocumentProfileFormatException>(() => DocumentProfileParser.Parse(RepeatsAndOmits));

        Assert.Equal(DocumentProfileDefect.DuplicateField, error.Defect);

        Assert.False(DocumentProfileParser.TryParse(RepeatsAndOmits, out DocumentProfile? profile, out DocumentProfileFormatException? refusal));
        Assert.Null(profile);
        Assert.NotNull(refusal);
    }

    [Fact]
    public void Parse_RefusesAReplyWhoseOnlyFaultIsAnOmissionMaskedByARepeat()
    {
        // The same cancellation with the repeat AFTER the omission, so the property-order dependence
        // the earlier count check had is closed in both directions rather than in the one that
        // happened to be written first.
        const string OmitsThenRepeats =
            """{"DocType":"Cross-Border Trading Legal Instruction","JurisdictionIso":"DE","DocRef":"CBTI-DE-2024","LayoutFamily":"contoso-country-manual-v4","Confidence":0.97,"Confidence":0.1}""";

        DocumentProfileFormatException error =
            Assert.Throws<DocumentProfileFormatException>(() => DocumentProfileParser.Parse(OmitsThenRepeats));

        Assert.Equal(DocumentProfileDefect.DuplicateField, error.Defect);
    }

    [Theory]
    [InlineData("\"JurisdictionIso\":\"DE\"", "\"JurisdictionIso\":42")]
    [InlineData("\"JurisdictionIso\":\"DE\"", "\"JurisdictionIso\":null")]
    [InlineData("\"Confidence\":0.97", "\"Confidence\":\"0.97\"")]
    public void Parse_RefusesAFieldOfTheWrongType(string original, string replacement)
    {
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(ValidProfile.Replace(original, replacement, StringComparison.Ordinal)));

        Assert.Equal(DocumentProfileDefect.WrongType, error.Defect);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void Parse_RefusesABlankStringBecauseBlankIsNotAnHonestUnknown(string blank)
    {
        // The prompt asks for the literal UNKNOWN with a lowered confidence, which routes the document
        // to a human. A blank would travel as data.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(
                ValidProfile.Replace("\"DocRef\":\"CBTI-DE-2024\"", $"\"DocRef\":\"{blank}\"", StringComparison.Ordinal)));

        Assert.Equal(DocumentProfileDefect.BlankValue, error.Defect);
        Assert.Contains("DocRef", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_AcceptsTheUnknownSentinelTheDesignAsksFor()
    {
        // The other half of the blank refusal: "I could not read this" has a channel, and it is a value
        // plus a low confidence. A parser that refused UNKNOWN would leave the model with no way to
        // say it at all - which is how a model ends up inventing one.
        DocumentProfile profile = DocumentProfileParser.Parse(
            """{"DocType":"UNKNOWN","JurisdictionIso":"UNKNOWN","DocRef":"UNKNOWN","Version":"UNKNOWN","LayoutFamily":"UNKNOWN","Confidence":0.05}""");

        Assert.Equal("UNKNOWN", profile.DocType);
        Assert.Equal(0.05d, profile.Confidence);
    }

    [Theory]
    [InlineData("1.4")]
    [InlineData("-0.1")]
    [InlineData("97")]
    public void Parse_RefusesAConfidenceOutsideTheUnitInterval(string confidence)
    {
        // Clamping would manufacture certainty the model never claimed - and 97 is the plausible one: a
        // model reporting a percentage would otherwise be clamped to 1.0 and every document would sail
        // past the routing threshold.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(WithConfidence(confidence)));

        Assert.Equal(DocumentProfileDefect.ConfidenceOutOfRange, error.Defect);
    }

    [Fact]
    public void Parse_ScrubsAHostileFieldNameOutOfTheRefusal()
    {
        // A model's reply is untrusted text from outside the estate, and the refusal it produces lands
        // in a log line, on a review-queue row and on an operator's terminal. Control characters forge
        // log lines; U+202E reorders everything rendered after it.
        //
        // Written as JSON escape sequences rather than as literal characters, for two reasons. A real
        // U+202E in this file would reverse how the rest of the line renders in an editor and in a
        // diff - the very effect under test - and a raw newline inside a JSON string is not JSON at
        // all, so the payload would be refused one step earlier and this test would pass without ever
        // reaching the sanitiser. Escaped, the parsed property NAME genuinely contains both characters.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(WithExtra("\"No\\ntes\\u202e\":\"x\"")));

        Assert.Equal(DocumentProfileDefect.UndeclaredField, error.Defect);
        Assert.DoesNotContain('\n', error.Message);
        Assert.DoesNotContain((char)0x202E, error.Message);

        // Replaced rather than dropped: a name rendered as "Notes" after the dangerous characters were
        // silently removed would send an operator hunting a field that, as far as they can see, is fine.
        Assert.Contains((char)0xFFFD, error.Message);
    }

    [Fact]
    public void Parse_BoundsAnAbsurdlyLongFieldNameBeforeRenderingIt()
    {
        // A model that returned a megabyte of one character would otherwise put it in a log line, a
        // queue row and a terminal. The bound is a denial-of-service control against whoever has to
        // read the failure.
        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(WithExtra($"\"{new string('x', 5000)}\":\"y\"")));

        Assert.Contains("[truncated]", error.Message, StringComparison.Ordinal);
        Assert.True(error.Message.Length < 1000, $"The refusal message is {error.Message.Length} characters long.");
    }

    [Fact]
    public void Parse_RefusesAnOverLongReplyBeforeParsingIt()
    {
        // The bound is the boundary's, not the provider's. An adapter's MaxOutputTokens is a fact
        // about one vendor and the agnosticism constraint makes the vendor replaceable, so a limit
        // living there would have to be re-argued per provider and would simply be absent behind a
        // stub. Measured: a 40 MB reply drove ~214 MB of allocation through JsonDocument.Parse before
        // any rule in this class was consulted.
        string oversize = new('x', DocumentProfileParser.MaxReplyLength + 1);

        DocumentProfileFormatException error =
            Assert.Throws<DocumentProfileFormatException>(() => DocumentProfileParser.Parse(oversize));

        Assert.Equal(DocumentProfileDefect.ReplyTooLarge, error.Defect);

        // And the refusal itself does not carry the reply into the message it produces - which would
        // hand the denial of service straight on to whoever reads the log.
        Assert.True(error.Message.Length < 500, $"The refusal message is {error.Message.Length} characters long.");
    }

    [Fact]
    public void Parse_RefusesAnOverLongFieldRatherThanTruncatingIt()
    {
        // Refused, not truncated: a silently shortened DocRef is a document reference that matches
        // nothing and looks perfectly fine. The cap is at the boundary so no downstream consumer -
        // a log line, a queue row, a column - has to remember it.
        string overlong = new('x', DocumentProfileParser.MaxFieldLength + 1);

        DocumentProfileFormatException error = Assert.Throws<DocumentProfileFormatException>(
            () => DocumentProfileParser.Parse(
                ValidProfile.Replace("\"DocRef\":\"CBTI-DE-2024\"", $"\"DocRef\":\"{overlong}\"", StringComparison.Ordinal)));

        Assert.Equal(DocumentProfileDefect.ValueTooLong, error.Defect);
        Assert.Contains("DocRef", error.Message, StringComparison.Ordinal);
        Assert.DoesNotContain(overlong, error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Parse_AcceptsAFieldExactlyAtTheCap()
    {
        // The boundary is inclusive, pinned so the constant has one reading rather than two.
        string atCap = new('x', DocumentProfileParser.MaxFieldLength);

        DocumentProfile profile = DocumentProfileParser.Parse(
            ValidProfile.Replace("\"DocRef\":\"CBTI-DE-2024\"", $"\"DocRef\":\"{atCap}\"", StringComparison.Ordinal));

        Assert.Equal(atCap, profile.DocRef);
    }

    [Fact]
    public void Parse_NormalisesNegativeZeroConfidence()
    {
        // -0.0 passes every range check (IEEE says -0.0 == 0.0) and then renders as "-0" in a log
        // line, an exception message and a review-queue row, where it reads as a corrupt value rather
        // than as the "no idea at all" it is. Normalising costs one comparison and removes a class of
        // confused incident reports.
        DocumentProfile profile = DocumentProfileParser.Parse(WithConfidence("-0.0"));

        Assert.Equal(0d, profile.Confidence);
        Assert.False(double.IsNegative(profile.Confidence));
    }

    [Fact]
    public void TryParse_ReportsARefusalInsteadOfThrowingIt()
    {
        // The shape the triage executor needs: a refused reply is an ordinary routing outcome (design 9)
        // rather than an error, and the executor has to record WHICH part of the contract broke on the
        // review-queue row it writes - so a bool would not be enough.
        Assert.True(DocumentProfileParser.TryParse(ValidProfile, out DocumentProfile? parsed, out DocumentProfileFormatException? none));
        Assert.NotNull(parsed);
        Assert.Null(none);

        Assert.False(DocumentProfileParser.TryParse("nope", out DocumentProfile? missing, out DocumentProfileFormatException? refusal));
        Assert.Null(missing);
        Assert.NotNull(refusal);
        Assert.Equal(DocumentProfileDefect.NotAJsonObject, refusal!.Defect);
    }

    [Fact]
    public void Parse_RejectsANullReply()
    {
        Assert.Throws<ArgumentNullException>(() => DocumentProfileParser.Parse(null!));
        Assert.Throws<ArgumentNullException>(() => DocumentProfileParser.TryParse(null!, out _, out _));
    }

    private static string WithConfidence(string confidence) =>
        ValidProfile.Replace("\"Confidence\":0.97", $"\"Confidence\":{confidence}", StringComparison.Ordinal);

    private static string WithExtra(string property) =>
        ValidProfile.Replace("{", "{" + property + ",", StringComparison.Ordinal);
}
